import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Landing page brand orange
        brand: {
          50: '#fff7ed',
          100: '#ffedd5',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          900: '#7c2d12',
        },
        // Material Design 3 tokens (admin panel)
        primary: '#9e3d00',
        'primary-container': '#c64f00',
        'primary-fixed': '#ffdbcd',
        'primary-fixed-dim': '#ffb595',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7c2e00',
        secondary: '#4e6073',
        'secondary-container': '#cfe2f9',
        'secondary-fixed': '#d1e4fb',
        'secondary-fixed-dim': '#b5c8df',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#526478',
        'on-secondary-fixed': '#091d2e',
        'on-secondary-fixed-variant': '#36485b',
        tertiary: '#0058bd',
        'tertiary-container': '#0070ec',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fefcff',
        'on-tertiary-fixed': '#001a41',
        'on-tertiary-fixed-variant': '#004494',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        surface: '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        'surface-tint': '#a23f00',
        'surface-variant': '#e1e3e4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'on-surface-variant': '#594238',
        outline: '#8c7166',
        'outline-variant': '#e0c0b2',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        'inverse-primary': '#ffb595',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
